In [3]:
import numpy as np
l=[3,4,6,8]
y=np.array(l)
print(y)

[3 4 6 8]


In [4]:
y.mean()

5.25

In [5]:
y.max()

8

In [6]:
y.sum()

21

In [7]:
y.min()

3

In [13]:
y=np.array([[5,4],[1,8]])
print(y)

[[5 4]
 [1 8]]


In [18]:
#position
y[0,0]

5

In [15]:
y[0,1]

4

In [16]:
y[1,0]

1

In [17]:
y[1,1]

8

In [24]:
y=np.mat("1,2;4,5")

In [25]:
print(y)

[[1 2]
 [4 5]]


In [26]:
y=np.mat("1,2,6;4,5,7;1,4,3")
print(y)

[[1 2 6]
 [4 5 7]
 [1 4 3]]


In [28]:
z=np.mat("5,6,8;7,6,4;2,4,9")
print(z)

[[5 6 8]
 [7 6 4]
 [2 4 9]]


In [30]:
y+z

matrix([[ 6,  8, 14],
        [11, 11, 11],
        [ 3,  8, 12]])

In [31]:
x=np.mat("1,2,3;4,5,6;7,8,9")
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
k=0
for i in range(0,3):
    k=k+x[i,0]
print(k) 

12


In [34]:
k=0
for i in range(0,3):
    k=k+x[0,i]
print(k) 

6


In [41]:
k=0
for i in range(0,3):
    k=k+x[i,0]+x[i,2]
print(k) 

30


In [39]:
k=0
w=0
s=k+w
for i in range(0,3):
    k=k+x[i,0]
    
for i in range(0,3):
    w=w+x[i,2]
    s=k+w
print(s)

30


In [10]:
import numpy as np
x=np.mat("1,2,3;4,5,6;7,8,9")
p=0
k=0
for i in range(0,2):
    for j in range(0,3):
        k=k+x[j,p]
    p=p+2
print(k)

30


In [13]:
import numpy as np
x=np.mat("1,2,3;4,5,6;7,8,9")
p=0
k=0
for i in range(0,3):
    for j in range(0,3):
        if(i==j):
            k=k+x[i,j]
        
print(k)

15


In [14]:
import numpy as np
x=np.mat("1,2,3;4,5,6;7,8,9")
p=0
k=0
for i in range(0,3):
    k=k+x[i,i]
print(k)

15


In [28]:
import numpy as np
x=np.mat("1,2,3;4,5,6;7,8,9")
p=0
k=0
for i in range(0,3):
    x[i,0]=6
print(x)

[[6 2 3]
 [6 5 6]
 [6 8 9]]


In [30]:
import numpy as np
x=np.mat("1,2,3;4,5,6;7,8,9")
p=0
k=0
for i in range(0,3):
    k=k+x[i,i]
    x[i,i]=3
print(x)

[[3 2 3]
 [4 3 6]
 [7 8 3]]


In [33]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [34]:
np.mat(x.reshape(3,3))

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [38]:
x=np.mat("1,2,3;4,5,6;7,8,9")
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# will print inverse of a matrix
x.getI()

matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [ ]:
#inverse,adjecent

In [47]:
x=np.mat("1,2,3;4,5,6;7,8,9")
print(x)
x.getT()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [44]:
x.shape

(3, 3)

In [48]:
x=np.mat("1,2,3;4,5,6;7,8,9")
print(x)
x.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [49]:
x.size

9

In [54]:
x=np.mat("1,2,3;4,5,6;7,8,9")
y=np.array([1,2,3])
x+y

matrix([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]])

In [62]:
x=np.mat("1,2,3;4,5,6;7,8,9")
y=np.mat("9,8,7;6,5,4;3,2,1")

x.dot(y)

matrix([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

In [67]:
x=np.array([1,2,3])
y=np.array([2,4,6])

In [69]:
x1=x**2
print(x1)
y1=y**2
print(y1)

[1 4 9]
[ 4 16 36]


In [70]:
x2=x1.sum()
print(x2)
y2=y1.sum()
print(y2)

14
56


In [72]:
x3=np.sqrt(x2)
print(x3)
y3=np.sqrt(y2)
print(y3)

3.7416573867739413
7.483314773547883
