In [17]:
X=[3,12,11,21,35,63,79,89,11,44,55,12,15,15]
a=[]
d=[]
e=[]
b=1
c=1
k=1
x=len(X)
print("length",x,X)
for i in range(0,x):
    if(x%3==0):
        k=x//3
        k=k+2
        b=k-2
        c=b-2    
               
    elif(x%2==0):
        k=x//2
        b=k//2
        b=b+1
        c=b-1
        
    else:
        k=(x-1)//2
        b=k//2
        b=b+2
        c=b//2

a=X[:k]
d=X[k:-c:]
e=X[x-c:]
      
print(k,a)
print(b,d)
print(c,e)


length 14 [3, 12, 11, 21, 35, 63, 79, 89, 11, 44, 55, 12, 15, 15]
7 [3, 12, 11, 21, 35, 63, 79]
4 [89, 11, 44, 55]
3 [12, 15, 15]


In [20]:
def f1():
    x=5
    y=3
    return(x+y)
f1()

8

In [22]:
def f2(x,y):
    z=x+y
    print(z)
f2(2,2)

4


In [26]:
def f2(x,y):
    z=x*y
    print(z)
f2(2,3)

6


In [34]:
def f2(x,y):
  
    if(x>y):
        z=x-y
    else:
        z=y-x
    print(z)
f2(1,3)

2


In [37]:
a=[3,4,6,9,8]
def f5(x):
    k=1
    for i in a:
        k=k+i
    print(k)
f5(a)

31


In [38]:
a=[3,4,6,9,8]
b=[3,4,12,6,8,54]
def f5(x):
    k=1
    for i in x:
        k=k+i
    print(k)
f5(a)
f5(b)

31
88


In [39]:
a=[3,4,6,9,8]
b=[3,4,12,6,8,54]
c=a+b
def f5(x):
    k=1
    for i in x:
        k=k+i
    print(k)
f5(a)
f5(b)
f5(c)

31
88
118


In [46]:

def f5(x,*y):
    y=list(y)
    k=0
    for i in y:
        k=k+i
 
    k=k+x
    print(k)
f5(3,4,12,6,8,54)


87


In [2]:
#lcm
x=40
y=60
k=y
while(k<(x*y+1)):
    if(k%x==0)&(k%y==0):
        print("lcm is",k)
        break
    k=k+1

lcm is 120


In [1]:
def lcm(x,*y):
    y=list(y)
    y.append(x)
    max=y[0]
    for i in y:
        if(i>max):
            max=i
        mul=1
        for i in y:
            mul=mul*i
    print(max)
    print(mul)
    for i in range(max,mul+1):
        count=0
        for j in y:
            if(i%j==0):
                count=count+1
        if(count==len(y)):
            print("lcm",i)
            break
    
lcm(13,14,50,20,10,12,15)


50
327600000
lcm 27300


In [ ]:
def lcm(x,*y):
    y=list(y)
    y.append(x)
    max=y[0]
    for i in y:
        if(i>max):
            max=i
        mul=1
        for i in y:
            mul=mul*i
    print(max)
    print(mul)
    for i in range(max,mul+1):
        count=0
        for j in y:
            if(i%j==0):
                count=count+1
        if(count==len(y)):
            print("lcm",i)
            break
    
lcm(13,14,50,20,10,12,15)


In [1]:
def hcf(x,*y):
    y=list(y)
    y.append(x)
    min=y[0]
    for i in y:
        if(i<min):
            min=i
        mul=1
        for i in y:
            mul=mul*i
    print(min)
    print(mul)
    for i in range(min,mul+1):
        count=0
        for j in y:
            if(i%j==0):
                count=count+1
        if(count==len(y)):
            print("hcf",i)
            break
        min=min-1
    
hcf(13,14,50,20,10,12,15)


In [11]:
def a(x,*y):
    y=list(y)
    y.append(x)
    z=len(y)
    for i in y:
        b=1
        k=0
        while(b<(y+1)):
            if(y%b==0):
                k=k+1
        b=b+1
        z=z+1
    if(k==2):
        print(y,"is prime")
    else:
        print(y,"is not prime")
        
a(13,14,50,20,10,12,15)

TypeError: can only concatenate list (not "int") to list

In [7]:
def a(x):
    
    k=0
    i=1
    while(i<(x+1)):
        if(x%i==0):
            k=k+1
        i=i+1
    if(k==2):
        print(x,"is prime")
    else:
        print(x,"is not prime")
        
a(7)

7 is prime


In [15]:
def even(x,*y):
    y=list(y)
    y.insert(0,x)
    for i in y:
        if(i%2==0):
            print(i)
        
        
even(10,1,25,6,8)

10
6
8


In [2]:
#function in function

def add(x,y):
    z=x+y
    print(z)
def sub(x,y):
    z=x-y
    print(z)
def a(x):
    if(x>4):
        add(5,3)
    else:
        sub(5,3)
a(9)

8


In [110]:
k=0
def a(k):
    print("india",k)
    k=k+1
    a(k)


a(0)






india 0
india 1
india 2
india 3
india 4
india 5
india 6
india 7
india 8
india 9
india 10
india 11
india 12
india 13
india 14
india 15
india 16
india 17
india 18
india 19
india 20
india 21
india 22
india 23
india 24
india 25
india 26
india 27
india 28
india 29
india 30
india 31
india 32
india 33
india 34
india 35
india 36
india 37
india 38
india 39
india 40
india 41
india 42
india 43
india 44
india 45
india 46
india 47
india 48
india 49
india 50
india 51
india 52
india 53
india 54
india 55
india 56
india 57
india 58
india 59
india 60
india 61
india 62
india 63
india 64
india 65
india 66
india 67
india 68
india 69
india 70
india 71
india 72
india 73
india 74
india 75
india 76
india 77
india 78
india 79
india 80
india 81
india 82
india 83
india 84
india 85
india 86
india 87
india 88
india 89
india 90
india 91
india 92
india 93
india 94
india 95
india 96
india 97
india 98
india 99
india 100
india 101
india 102
india 103
india 104
india 105
india 106
india 107
india 108
india 109
india 110


india 967
india 968
india 969
india 970
india 971
india 972
india 973
india 974
india 975
india 976
india 977
india 978
india 979
india 980
india 981
india 982
india 983
india 984
india 985
india 986
india 987
india 988
india 989
india 990
india 991
india 992
india 993
india 994
india 995
india 996
india 997
india 998
india 999
india 1000
india 1001
india 1002
india 1003
india 1004
india 1005
india 1006
india 1007
india 1008
india 1009
india 1010
india 1011
india 1012
india 1013
india 1014
india 1015
india 1016
india 1017
india 1018
india 1019
india 1020
india 1021
india 1022
india 1023
india 1024
india 1025
india 1026
india 1027
india 1028
india 1029
india 1030
india 1031
india 1032
india 1033
india 1034
india 1035
india 1036
india 1037
india 1038
india 1039
india 1040
india 1041
india 1042
india 1043
india 1044
india 1045
india 1046
india 1047
india 1048
india 1049
india 1050
india 1051
india 1052
india 1053
india 1054
india 1055
india 1056
india 1057
india 1058
india 1059
india 1060

india 2044
india 2045
india 2046
india 2047
india 2048
india 2049
india 2050
india 2051
india 2052
india 2053
india 2054
india 2055
india 2056
india 2057
india 2058
india 2059
india 2060
india 2061
india 2062
india 2063
india 2064
india 2065
india 2066
india 2067
india 2068
india 2069
india 2070
india 2071
india 2072
india 2073
india 2074
india 2075
india 2076
india 2077
india 2078
india 2079
india 2080
india 2081
india 2082
india 2083
india 2084
india 2085
india 2086
india 2087
india 2088
india 2089
india 2090
india 2091
india 2092
india 2093
india 2094
india 2095
india 2096
india 2097
india 2098
india 2099
india 2100
india 2101
india 2102
india 2103
india 2104
india 2105
india 2106
india 2107
india 2108
india 2109
india 2110
india 2111
india 2112
india 2113
india 2114
india 2115
india 2116
india 2117
india 2118
india 2119
india 2120
india 2121
india 2122
india 2123
india 2124
india 2125
india 2126
india 2127
india 2128
india 2129
india 2130
india 2131
india 2132
india 2133
india 2134

RecursionError: maximum recursion depth exceeded while calling a Python object

In [48]:
#factorial using function

def fact(x):
    if(x==0):
        return 1
    else:
        return(x*fact(x-1))
    print(x)
        
    
fact(6)

720

In [54]:
def fact(x):
    if(x==0):
        return 0
    
    else:
        return(x+fact(x-1))
    print(x)
        
    
fact(5)

15

In [63]:
#global 

x=4
def f1(y):
    global x
    x=y+3
    print(x)
print(x)
    
f1(4)
print(x)

4
7
7


In [64]:
print(x)

7


In [65]:
l=[3,4,2,8]
y=2*l
print(y)

[3, 4, 2, 8, 3, 4, 2, 8]


In [67]:
l=[3,4,2,8]
y=2*l
print(y)
x1=[8,9,7,2]
y=l+x1
print(y)

[3, 4, 2, 8, 3, 4, 2, 8]
[3, 4, 2, 8, 8, 9, 7, 2]


In [73]:
y=lambda a,b:a+b
print(y)
y(3,4)


<function <lambda> at 0x00000189B123ED90>


7

In [74]:
y=lambda a,b:a-b
print(y)
y(3,4)


<function <lambda> at 0x00000189B123E950>


-1

In [82]:
l=[3,4,7,12,9,16]
p=list(filter(lambda k:k%2==0,l))
q=list(filter(lambda k:k%2,l))
print(p)
print(q)


[4, 12, 16]
[3, 7, 9]


In [7]:
l=[3,4,7,12,9,16]
def f1(x):
    return x%2==0
p=list(filter(f1,l))

print(p)




[4, 12, 16]


In [94]:
l=[3,4,7,12,9,16]
def f2(x):
    return x%2==0
p=list(map(f1,l))
print(p)

[False, True, False, True, False, True]


In [105]:
n=10
r=4
def f1(x):
    if(x==0):
        return 1
    else:
        return(x*f1(x-1))
p=f1(n)
q=f1(r)
r=f1(n-r)
s=p//(q*r)

print(s)

    

    

210


In [116]:
import numpy as np
x1=np.array([3,4,6])
y1=np.array([4,6,8])
z=2*x1
print(z)

[ 6  8 12]


In [114]:
import numpy as np
l1=[3,4,5,6,7]
y=np.array(l1)

print(y)

[3 4 5 6 7]


In [117]:
import numpy as np
l=[3,4,6,8]
y=np.array(l)
z=y**2
print(z)


[ 9 16 36 64]


In [4]:
import numpy as np
x1=[4,6,8,10]
x2=[2,3,4,5]
x=np.array(x1)
y=np.array(x2)
z=x**2-y**2
a=np.sum(z)
print(a)

162


In [7]:
import numpy as np
x1=[4,6,8,10]
x2=[2,3,4,5]
x=np.array(x1)
y=np.array(x2)
z=x**2-y**2
print(z)
k=0
for i in z:
    k=k+i
print(k)


[12 27 48 75]
162
